# Generated by Django 3.2.4 on 2023-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapiass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asignacionpsicologo',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='asignacionpsicologo',
            name='dia_semana',
            field=models.ManyToManyField(to='terapiass.DiaSemana'),
        ),
    ]
