# Generated by Django 3.2.4 on 2023-10-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0004_rename_psicologos_psicologo'),
        ('terapiass', '0002_auto_20231020_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapia',
            name='psicologos',
            field=models.ManyToManyField(through='terapiass.AsignacionPsicologo', to='psicologo.Psicologo'),
        ),
    ]
