# Generated by Django 3.2.4 on 2023-10-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapiass', '0003_terapia_psicologos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapia',
            name='psicologos',
        ),
    ]
