# Generated by Django 3.2.4 on 2023-10-25 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terapiass', '0004_remove_terapia_psicologos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('asignacion_psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapiass.asignacionpsicologo')),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapiass.diasemana')),
            ],
        ),
    ]
