# Generated by Django 4.2.4 on 2024-04-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0004_rename_psicologos_psicologo'),
        ('terapiass', '0009_alter_diagnostico_nombre_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionpsicologo',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='asignacionpsicologo',
            name='psicologo',
        ),
        migrations.RemoveField(
            model_name='asignacionpsicologo',
            name='terapia',
        ),
        migrations.RemoveField(
            model_name='horarioterapia',
            name='asignacion_psicologo',
        ),
        migrations.AddField(
            model_name='terapia',
            name='dias_trabajo',
            field=models.ManyToManyField(to='terapiass.diasemana'),
        ),
        migrations.AddField(
            model_name='terapia',
            name='psicologo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psicologo.psicologo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AsignacionEstudiante',
        ),
        migrations.DeleteModel(
            name='AsignacionPsicologo',
        ),
        migrations.DeleteModel(
            name='HorarioTerapia',
        ),
    ]
