# Generated by Django 4.2.4 on 2024-04-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapiass', '0010_remove_asignacionpsicologo_dia_semana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapia',
            name='fecha_inicio',
        ),
    ]
