# Generated by Django 4.2.4 on 2024-04-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0004_rename_psicologos_psicologo'),
        ('terapiass', '0011_remove_terapia_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapia',
            name='psicologo',
        ),
        migrations.AddField(
            model_name='terapia',
            name='psicologo',
            field=models.ManyToManyField(to='psicologo.psicologo'),
        ),
    ]
