# Generated by Django 4.2.4 on 2024-04-20 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0004_rename_psicologos_psicologo'),
        ('terapiass', '0012_remove_terapia_psicologo_terapia_psicologo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapia',
            name='dias_trabajo',
        ),
        migrations.RemoveField(
            model_name='terapia',
            name='psicologo',
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapiass.diasemana')),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='terapiass.terapia')),
            ],
        ),
        migrations.AddField(
            model_name='terapia',
            name='psicologo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psicologo.psicologo'),
            preserve_default=False,
        ),
    ]
