# Generated by Django 4.2.4 on 2024-04-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_representante_servicios'),
        ('terapiass', '0013_remove_terapia_dias_trabajo_remove_terapia_psicologo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.estudiante')),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='terapiass.terapia')),
            ],
        ),
    ]
