# Generated by Django 4.2.4 on 2024-04-29 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_representante_servicios'),
        ('terapiass', '0014_asignacionestudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionestudiante',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='terapia',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.estudiante'),
            preserve_default=False,
        ),
    ]
