# Generated by Django 4.2.4 on 2024-04-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terapiass', '0015_remove_asignacionestudiante_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionFechaTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechaTerapia', to='terapiass.terapia')),
            ],
        ),
        migrations.DeleteModel(
            name='AsignacionEstudiante',
        ),
    ]
