# Generated by Django 4.2.4 on 2024-05-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapiass', '0018_asistencia_delete_registroasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='horas_restantes',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
