# Generated by Django 4.2.4 on 2024-05-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0004_rename_psicologos_psicologo'),
        ('servicios', '0004_paquete'),
        ('terapiass', '0019_asistencia_horas_restantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('fecha_inicio', models.DateField()),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapiass.diasemana')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.paquete')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='psicologo.psicologo')),
            ],
        ),
    ]
