# Generated by Django 4.2.4 on 2024-05-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapiass', '0020_horarioterapia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='terapia',
        ),
        migrations.RemoveField(
            model_name='terapia',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='terapia',
            name='paquete',
        ),
        migrations.RemoveField(
            model_name='terapia',
            name='psicologo',
        ),
        migrations.DeleteModel(
            name='AsignacionFechaTerapia',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Terapia',
        ),
    ]
