# Generated by Django 4.2.4 on 2024-05-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapiass', '0021_remove_horario_dia_semana_remove_horario_terapia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioterapia',
            name='fecha_dia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
