# Generated by Django 4.2.4 on 2023-09-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_alter_estudiante_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('edad_biologica', models.IntegerField()),
                ('edad_cognitiva_lenguaje_verbal', models.IntegerField()),
                ('edad_cognitiva_lenguaje_comprensivo', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.IntegerField()),
                ('tiempo_previsto', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('actividad_lenguaje', models.TextField()),
                ('actividad_cognitiva', models.TextField()),
                ('actividad_sensorial', models.TextField()),
                ('actividades_internalizadas', models.TextField()),
                ('actividades_reforzar', models.TextField()),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion')),
            ],
        ),
    ]
