# Generated by Django 4.2.4 on 2024-01-22 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terapiass', '0009_alter_diagnostico_nombre_diagnostico'),
        ('planificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapiass.diagnostico'),
        ),
    ]
