# Generated by Django 4.2.4 on 2023-10-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_alter_horario_hora_fin_alter_horario_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(max_length=10),
        ),
    ]
