# Generated by Django 4.2.4 on 2023-09-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_alter_estudiante_fecha'),
        ('planificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('fecha', models.DateField()),
                ('observacion_conducta', models.CharField(max_length=100)),
                ('temas_trabajados', models.CharField(max_length=400)),
                ('avance', models.CharField(max_length=300)),
                ('firma_terapeuta', models.CharField(max_length=100)),
                ('revisado_por', models.CharField(max_length=100)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.estudiante')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificaciones.planificacion')),
            ],
        ),
    ]
