# Generated by Django 4.2.4 on 2024-01-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_alter_bitacora_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='avance',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='firma_terapeuta',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='observacion_conducta',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='revisado_por',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='temas_trabajados',
        ),
        migrations.CreateModel(
            name='NuevaBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion_conducta', models.CharField(max_length=100)),
                ('temas_trabajados', models.CharField(max_length=400)),
                ('avance', models.CharField(max_length=300)),
                ('firma_terapeuta', models.CharField(max_length=100)),
                ('revisado_por', models.CharField(max_length=100)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitacora.bitacora')),
            ],
        ),
    ]
