# Generated by Django 4.2.4 on 2024-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_remove_bitacora_avance_remove_bitacora_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevabitacora',
            name='asistencias',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], default='si', max_length=10),
        ),
    ]
