# Generated by Django 4.2.4 on 2024-01-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0004_nuevabitacora_asistencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevabitacora',
            name='avance',
            field=models.CharField(choices=[('mejorando', 'mejorando'), ('regular', 'regular'), ('retroceso', 'retroceso')], default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='nuevabitacora',
            name='observacion_conducta',
            field=models.CharField(choices=[('excelente', 'excelente'), ('buena', 'buena'), ('regular', 'regular')], default='buena', max_length=50),
        ),
    ]
