# Generated by Django 4.2.4 on 2023-09-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='psicologo/'),
        ),
    ]
