# Generated by Django 4.2.4 on 2023-09-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0002_alter_psicologo_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Psicologo',
            new_name='Psicologos',
        ),
    ]
