# Generated by Django 4.2.4 on 2023-08-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
