# Generated by Django 4.2.4 on 2023-08-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicios_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='imagen',
        ),
    ]
