# Generated by Django 3.2.4 on 2023-10-14 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_estudiante_fecha'),
        ('servicios', '0003_remove_servicios_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField(default=1)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.representante')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios')),
            ],
        ),
    ]
