# Generated by Django 4.2.4 on 2024-05-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_representante_servicios'),
        ('servicios', '0004_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='estudiante',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='usuario.estudiante'),
            preserve_default=False,
        ),
    ]
