# Generated by Django 4.2.4 on 2023-09-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=7)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cedula', models.CharField(max_length=10)),
                ('servicios', models.CharField(choices=[('Terapia de Lenguaje', 'Terapia de Lenguaje'), ('Terapia Neuropedagógica', 'Terapia Neuropedagógica'), ('Nivelación', 'Nivelacion'), ('Taller de estimulación temprana', 'Taller de estimulación temprana'), ('Estimulación temprana', 'Taller de estimulación temprana'), ('Talleres', 'Talleres'), ('Estimulacion cognitiva', 'Estimulacion cognitiva'), ('Estimulacion de lenguaje', 'Estimulacion de lenguaje')], default='Terepia de Lenguaje', max_length=50)),
                ('otra_terapia', models.CharField(max_length=50)),
                ('conocido', models.CharField(max_length=100)),
                ('observacion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('año_educacion', models.PositiveIntegerField()),
                ('institucion_educativa', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('motivo', models.TextField(max_length=500)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.representante')),
            ],
        ),
    ]
