# Generated by Django 4.2.4 on 2024-01-24 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_estudiante_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.representante'),
        ),
    ]
