# Generated by Django 4.2.4 on 2024-01-24 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_estudiante_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='edad',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='M', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='representante',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='usuario.representante'),
            preserve_default=False,
        ),
    ]
