# Generated by Django 4.2.4 on 2024-04-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_estudiante_edad_alter_estudiante_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='servicios',
            field=models.CharField(choices=[('Terapia de Lenguaje', 'Terapia de Lenguaje'), ('Terapia Neuropedagógica', 'Terapia Neuropedagógica'), ('Nivelación', 'Nivelacion'), ('Taller de estimulación temprana', 'Taller de estimulación temprana'), ('Estimulación temprana', 'Estimulación temprana'), ('Talleres', 'Talleres'), ('Estimulacion cognitiva', 'Estimulacion cognitiva'), ('Estimulacion de lenguaje', 'Estimulacion de lenguaje')], default='Terepia de Lenguaje', max_length=50),
        ),
    ]
