# Generated by Django 4.2.4 on 2024-05-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_representante_servicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'permissions': [('can_create_estudiante', 'Can create Estudiante')]},
        ),
        migrations.AlterModelOptions(
            name='representante',
            options={'permissions': [('can_create_representante', 'Can create Representante')]},
        ),
    ]
