# Generated by Django 4.2.4 on 2024-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_estudiante_options_alter_representante_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], default='F', max_length=50),
        ),
    ]
