# Generated by Django 4.2.4 on 2024-06-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_estudiante_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('F', 'Masculino')], default='F', max_length=1),
        ),
    ]
