# Generated by Django 4.2.4 on 2024-06-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_estudiante_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='edad',
        ),
    ]
