# Generated by Django 4.2.4 on 2024-06-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_remove_estudiante_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='edad',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
