# Generated by Django 4.2.4 on 2024-06-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_estudiante_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1),
        ),
    ]
