# Generated by Django 3.2.4 on 2023-10-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psicologo', '0004_rename_psicologos_psicologo'),
        ('servicios', '0004_paquete'),
        ('usuario', '0002_alter_estudiante_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.paquete')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicologo.psicologo')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.estudiante')),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapias.terapia')),
            ],
        ),
    ]
