# Generated by Django 3.2.4 on 2023-10-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20),
        ),
    ]
