# Generated by Django 3.2.4 on 2023-10-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapias', '0002_alter_terapia_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='dia_semana',
            field=models.CharField(max_length=50),
        ),
    ]
